"""Model-package dependency allowlist used by architecture tests."""

MODEL_ALLOWED = {
    "data": set(),
    "instrument": set(),
    "automation": {"data", "instrument"},
    "structure": set(),
    "parameters": set(),
    "constraint_expression": {"parameters"},
    "constraint_resolution": {"constraint_expression", "parameters"},
    "project_parameter_graph": {"parameters"},
    "project_joint_ranking": {"parameters"},
    "progress": set(),
    "mcmc_sampling": set(),
    "mcmc_samples": {"mcmc_sampling"},
    "sld_bands": set(),
    "slab_stack": set(),
    "fitting": {"data", "instrument", "structure", "parameters", "progress", "slab_stack", "search"},
    "search": set(),
    "evaluation": {"data", "fitting", "instrument", "parameters", "slab_stack"},
    "diagnostic_calibration": {"evaluation", "fitting", "diagnostic_work"},
    "diagnostic_work": {"fitting"},
    "inference": {"instrument", "fitting", "diagnostic_calibration"},
    "bootstrap": {"fitting", "bootstrap_intervals"},
    "bootstrap_intervals": set(),
    "joint_bootstrap_provenance": {"bootstrap", "provenance"},
    "profile": {"fitting"},
    "provenance": {"fitting", "evaluation", "diagnostic_calibration"},
    "analysis": {
        "inference",
        "bootstrap",
        "joint_bootstrap_provenance",
        "profile",
        "data",
        "parameters",
        "fitting",
        "mcmc_samples",
        "mcmc_sampling",
        "sld_bands",
    },
    "project": {
        "automation",
        "data",
        "instrument",
        "structure",
        "parameters",
        "fitting",
        "analysis",
        "project_parameter_graph",
        "project_joint_ranking",
        "joint_bootstrap_provenance",
    },
    "operations": {"automation", "fitting", "analysis", "project"},
    "export": {"data", "fitting", "analysis", "project", "operations"},
}
