"""The complete supported Python API for XRR project workflows."""

from xrr_fitter.model.analysis import (
    FitResult,
    McmcConfig,
    McmcReport,
    ParameterProfile,
    StructureEvidence,
    UncertaintyReport,
)
from xrr_fitter.model.automation import (
    ImportBatchPreview,
    ImportFailure,
    ImportFilePreview,
    MeasurementPreset,
)
from xrr_fitter.model.data import BeamSpec, DataColumnMapping, PreparedData
from xrr_fitter.model.export import ExportManifest
from xrr_fitter.model.fitting import FitConfig, FitProgress
from xrr_fitter.model.instrument import InstrumentSpec
from xrr_fitter.model.operations import (
    FitReadiness,
    OperationError,
    OperationEvent,
    ProjectFitResult,
    ProjectImportResult,
)
from xrr_fitter.model.parameters import (
    ParameterDefinition,
    ParameterReference,
    ParameterSetting,
    SharingRule,
)
from xrr_fitter.model.project import (
    DatasetProject,
    OxideDecision,
    ProjectUiState,
    ProjectValidation,
    ScalePriorState,
    SourceUpdatePreview,
    ValidationIssue,
    XrrProject,
)
from xrr_fitter.model.structure import (
    GradientLayerSpec,
    LayerSpec,
    MaterialSpec,
    OxideSuggestion,
    PeriodicBlock,
    StructureSpec,
)
from xrr_fitter.services.datasets import (
    add_dataset,
    import_data,
    import_dataset_batch,
    preview_import_batch,
    preview_source_update,
    remove_dataset,
    set_fit_mask,
    set_instrument,
)
from xrr_fitter.services.exports import export_result
from xrr_fitter.services.fitting import fit_project, preflight_fit, run_mcmc
from xrr_fitter.services.parameters import (
    accept_source_update,
    describe_parameters,
    set_parameter_settings,
    set_sharing_rules,
    validate_parameter_settings,
    validate_sharing_rules,
)
from xrr_fitter.services.projects import (
    clear_fit_results,
    inspect_sources,
    load_project,
    new_project,
    save_project,
    select_active_dataset,
    select_candidate,
    set_batch_mode,
    set_expert_mode,
    set_workspace_state,
)
from xrr_fitter.services.structures import (
    accept_oxide_suggestion,
    analyze_structure,
    record_oxide_decision,
    set_structure,
    suggest_oxide_layers,
    validate_structure,
)
from xrr_fitter.services.workers import (
    OperationJob,
    start_fit_job,
    start_mcmc_job,
)

__all__ = (
    "BeamSpec",
    "DataColumnMapping",
    "DatasetProject",
    "ExportManifest",
    "FitConfig",
    "FitProgress",
    "FitReadiness",
    "FitResult",
    "GradientLayerSpec",
    "ImportBatchPreview",
    "ImportFilePreview",
    "ImportFailure",
    "InstrumentSpec",
    "LayerSpec",
    "MaterialSpec",
    "MeasurementPreset",
    "McmcConfig",
    "McmcReport",
    "OperationError",
    "OperationEvent",
    "OperationJob",
    "OxideDecision",
    "OxideSuggestion",
    "ParameterDefinition",
    "ParameterProfile",
    "ParameterReference",
    "ParameterSetting",
    "PeriodicBlock",
    "PreparedData",
    "ProjectFitResult",
    "ProjectImportResult",
    "ProjectUiState",
    "ProjectValidation",
    "ScalePriorState",
    "SharingRule",
    "SourceUpdatePreview",
    "StructureEvidence",
    "StructureSpec",
    "UncertaintyReport",
    "ValidationIssue",
    "XrrProject",
    "accept_oxide_suggestion",
    "accept_source_update",
    "add_dataset",
    "analyze_structure",
    "clear_fit_results",
    "describe_parameters",
    "export_result",
    "fit_project",
    "import_data",
    "import_dataset_batch",
    "inspect_sources",
    "load_project",
    "new_project",
    "preflight_fit",
    "preview_import_batch",
    "preview_source_update",
    "record_oxide_decision",
    "remove_dataset",
    "run_mcmc",
    "save_project",
    "select_active_dataset",
    "select_candidate",
    "set_batch_mode",
    "set_expert_mode",
    "set_fit_mask",
    "set_instrument",
    "set_parameter_settings",
    "set_sharing_rules",
    "set_structure",
    "set_workspace_state",
    "start_fit_job",
    "start_mcmc_job",
    "suggest_oxide_layers",
    "validate_parameter_settings",
    "validate_sharing_rules",
    "validate_structure",
)
